---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valheim-data-pvc
  # namespace: valheim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  volumeName: nfs-valheim-data
  storageClassName: ""

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valheim-config-pvc
  # namespace: valheim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: nfs-valheim-config
  storageClassName: ""
