---
apiVersion: v1
kind: Service
metadata:
  name: valheim
  # namespace: valheim
spec:
  type: NodePort
  selector:
    app: game
    game: valheim
  ports:
    - name: game
      port: 2456
      targetPort: 2456
      nodePort: 2456
      protocol: UDP
    - name: query
      port: 2457
      targetPort: 2457
      nodePort: 2457
      protocol: UDP
    # - name: steam-api
    #   port: 27015
    #   targetPort: 27015
    #   nodePort: 27015
    #   protocol: UDP

---
apiVersion: v1
kind: Service
metadata:
  name: valheim-web
  # namespace: valheim
spec:
  type: ClusterIP
  selector:
    app: game
    game: valheim
  ports:
    - name: supervisord
      port: 9001
      targetPort: 9001
      protocol: TCP
    - name: status
      port: 80
      targetPort: 80
      protocol: TCP
