---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-steamcmd-scripts
  # namespace: subnautica
data:
  update.txt: |-
    @ShutdownOnFailedCommand 1
    @NoPromptForPassword 1
    @sSteamCmdForcePlatformType windows
    force_install_dir /software/subnautica
    login anonymous
    app_update 264710 -beta legacy validate
    quit
