---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: subnautica
  # namespace: subnautica
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  volumeName: pv-subnautica
  storageClassName: ""

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nitrox
  # namespace: subnautica
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-nitrox
  storageClassName: ""
