---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: palworld
  namespace: palworld
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
  volumeName: nfs-palworld
  storageClassName: ""
