---
apiVersion: v1
kind: Service
metadata:
  name: the-forest
  namespace: the-forest
spec:
  selector:
    app: game
    game: the-forest
  type: NodePort
  ports:
  - name: steam-tcp
    port: 8766
    targetPort: 8766
    nodePort: 8766
    protocol: TCP
  - name: steam-udp
    port: 8766
    targetPort: 8766
    nodePort: 8766
    protocol: UDP
  - name: game-tcp
    port: 27015
    targetPort: 27015
    nodePort: 27015
    protocol: TCP
  - name: game-udp
    port: 27015
    targetPort: 27015
    nodePort: 27015
    protocol: UDP
  - name: query-tcp
    port: 27016
    targetPort: 27016
    nodePort: 27016
    protocol: TCP
  - name: query-udp
    port: 27016
    targetPort: 27016
    nodePort: 27016
    protocol: UDP
