---
apiVersion: v1
kind: Service
metadata:
  name: dont-starve-together
  namespace: dont-starve-together
spec:
  selector:
    app: game
    game: dont-starve-together
  type: NodePort
  ports:
  - name: master
    port: 10999
    targetPort: 10999
    nodePort: 10999
    protocol: UDP
  - name: caves
    port: 11000
    targetPort: 11000
    nodePort: 11000
    protocol: UDP
  - name: steam
    port: 12346
    targetPort: 12346
    nodePort: 12346
    protocol: UDP
  - name: steam-query
    port: 12347
    targetPort: 12347
    nodePort: 12347
    protocol: UDP
